[project]
name = "bma-opendata-python-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.5,<3.0",
    "requests>=2.31,<3.0",
]
